const master = [
  {
    name: "Inbox",
    url: "/inbox",
    navigationUrl: "/digit-ui/employee/fsm/inbox",
    component: "Inbox",
    private: true,
  },
  {
    name: "FSTP Inbox",
    url: "/fstp-inbox",
    navigationUrl: "/digit-ui/employee/fsm/fstp-inbox",
    component: "FstpInbox",
    private: true,
  },
  {
    name: "Employee New Application",
    url: "/new-application",
    navigationUrl: "/digit-ui/employee/fsm/new-application",
    component: "NewApplication",
    private: true,
  },
  {
    name: "Modify Application",
    url: "/modify-application/:id",
    navigationUrl: "/digit-ui/employee/fsm/modify-application/:id",
    component: "EditApplication",
    private: true,
  },
  {
    name: "Employee Application Details",
    url: "/application-details/:id",
    navigationUrl: "/digit-ui/employee/fsm/application-details/:id",
    component: "EmployeeApplicationDetails",
    private: false,
  },
  {
    name: "FSTP Operator Details",
    url: "/fstp-operator-details/:id",
    navigationUrl: "/digit-ui/employee/fsm/fstp-operator-details/:id",
    component: "FstpOperatorDetails",
    private: true,
  },
  {
    name: "Collect Payment",
    url: "/collect-payment",
    navigationUrl: "/digit-ui/employee/fsm/collect-payment",
    component: "CollectPayment",
    private: true,
  },
  {
    name: "Application Audit",
    url: "/application-audit/:id",
    navigationUrl: "/digit-ui/employee/fsm/application-audit/:id",
    component: "ApplicationAudit",
    private: false,
  },
  {
    name: "Search Application",
    url: "/search",
    navigationUrl: "/digit-ui/employee/fsm/search",
    component: "SearchApplication",
    private: true,
  },
  {
    name: "New Application Citizen",
    url: "/new-application",
    navigationUrl: "/digit-ui/employee/fsm/new-application",
    component: "NewApplicationCitizen",
    private: false,
  },
  {
    name: "My Application",
    url: "/my-applications",
    navigationUrl: "/digit-ui/employee/fsm/my-applications",
    component: "MyApplications",
    private: false,
  },
  {
    name: "Application Details Citizen",
    url: "/application-details/:id",
    navigationUrl: "/digit-ui/employee/fsm/application-details/:id",
    component: "ApplicationDetails",
    private: false,
  },
  {
    name: "Citien Rating",
    url: "/rate/:id",
    navigationUrl: "/digit-ui/employee/fsm/rate/:id",
    component: "SelectRating",
    private: false,
  },
  {
    name: "DSO Dashboard",
    url: "/dso-dashboard",
    navigationUrl: "/digit-ui/employee/fsm/dso-dashboard",
    component: "DsoDashboard",
    private: true,
  },
];

export default master;
